// vue/server_demo/src/views/Home/index.vue
<!--
 * @Author: your name
 * @Date: 2021-10-12 16:41:52
 * @LastEditTime: 2021-10-12 19:47:58
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \day1\server_demo\src\views\Home\index.vue
-->
<template>
  <div>首页</div>
</template>

<script>
export default {
  created() {
    console.log(this.$store.state.user.name);
  },
};
</script>

<style>
</style>

// myapp/src/pages/home/index.tsx
/*
 * @Author: your name
 * @Date: 2022-03-05 20:28:13
 * @LastEditTime: 2022-03-06 13:47:15
 * @LastEditors: Please set LastEditors
 * @Description: 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 * @FilePath: \ZhaoZiAng0228\myapp\src\pages\home\index.tsx
 */

import { useState } from "react"

const Home = () => {
    const [arr, setArr] = useState('1')
    console.log(arr);

    return (
        <div>1</div>
    )
}

export default Home
